[build]
    publish = "build"
    command = "npm run build"

[dev]
    command = "npm start"
    port = 3001

[context.production.environment]
    NODE_ENV = "production"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200